# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifOvniBoJtO-K2k3lF27OygixKUVdIsY
"""

import yfinance as yf
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Define the OMXN40 universe (example tickers)
tickers = ['NOVO-B.CO', 'VOLV-B.ST', 'DNB.OL', 'ORSTED.CO', 'NDA-FI.HE',
           'ATCO-A.ST', 'TEL.OL', 'SHB-A.ST', 'ERIC-B.ST', 'TRYG.CO']

# Add error handling function
def safe_get(info_dict, key, default=0):
    """Safely get values from yfinance info, handling missing data"""
    value = info_dict.get(key)
    if value is None or (isinstance(value, float) and value == 0):
        return default
    return value

data = {}
for ticker in tickers:
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        data[ticker] = {
            'name': safe_get(info, 'longName', 'N/A'),
            'pe_ratio': safe_get(info, 'trailingPE', 0),
            'pb_ratio': safe_get(info, 'priceToBook', 0),
            'roe': safe_get(info, 'returnOnEquity', 0),
            'operating_margin': safe_get(info, 'operatingMargins', 0),
            'debt_to_equity': safe_get(info, 'debtToEquity', 0),
            'revenue_growth_5y': safe_get(info, 'revenueGrowth', 0),
            'market_cap': safe_get(info, 'marketCap', 0)  # Add market cap for context
        }
        print(f"✓ Successfully fetched data for {ticker}")
    except Exception as e:
        print(f"✗ Error fetching data for {ticker}: {e}")
        continue

# Create the master DataFrame
df = pd.DataFrame.from_dict(data, orient='index')

# Add composite scoring
def calculate_score(row):
    """Calculate overall investment score"""
    score = 0
    # Valuation (30% weight)
    if row['pe_ratio'] > 0 and row['pe_ratio'] < 15:
        score += 30
    elif row['pe_ratio'] > 0 and row['pe_ratio'] < 25:
        score += 15

    # Profitability (30% weight)
    if row['roe'] > 0.15:
        score += 30
    elif row['roe'] > 0.10:
        score += 15

    # Financial Health (20% weight)
    if row['debt_to_equity'] > 0 and row['debt_to_equity'] < 0.5:
        score += 20
    elif row['debt_to_equity'] > 0 and row['debt_to_equity'] < 1.0:
        score += 10

    # Growth (20% weight)
    if row['revenue_growth_5y'] > 0.05:
        score += 20
    elif row['revenue_growth_5y'] > 0:
        score += 10

    return score

df['investment_score'] = df.apply(calculate_score, axis=1)

print("\n" + "="*80)
print("NORDIC STOCKS ANALYSIS - Financial Metrics")
print("="*80)
print(df.to_string())
print("="*80)

# Display top ranked companies
df_ranked = df.sort_values('investment_score', ascending=False)
print("\n" + "="*80)
print("TOP RANKED COMPANIES BY INVESTMENT SCORE")
print("="*80)
top_companies = df_ranked[['name', 'investment_score', 'pe_ratio', 'roe', 'debt_to_equity', 'revenue_growth_5y']]
print(top_companies.to_string())
print("="*80)

# Create investment score ranking visualization
plt.figure(figsize=(12, 8))
df_ranked_viz = df.sort_values('investment_score', ascending=True)

# Create horizontal bar chart
bars = plt.barh(df_ranked_viz.index, df_ranked_viz['investment_score'],
                color=['red' if x < 40 else 'orange' if x < 70 else 'green' for x in df_ranked_viz['investment_score']])

# Add value labels on bars
for bar, score in zip(bars, df_ranked_viz['investment_score']):
    plt.text(bar.get_width() - 5, bar.get_y() + bar.get_height()/2,
             f'{score:.0f}', ha='right', va='center', color='white', fontweight='bold')

plt.xlabel('Investment Score (0-100)')
plt.title('Nordic Stocks - Investment Score Ranking\n(Quantitative Screening Results)', fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3, axis='x')
plt.axvline(x=70, color='green', linestyle='--', alpha=0.7, label='Strong Candidate (>70)')
plt.axvline(x=40, color='red', linestyle='--', alpha=0.7, label='Weak Candidate (<40)')
plt.legend()

plt.tight_layout()
plt.savefig('nordic_stocks_ranking.png', dpi=300, bbox_inches='tight')
print("\nInvestment ranking chart saved as 'nordic_stocks_ranking.png'")

# Create improved visualization with labels
plt.figure(figsize=(14, 8))

# Separate growing and declining companies
df_growing = df[df['revenue_growth_5y'] >= 0].copy()
df_declining = df[df['revenue_growth_5y'] < 0].copy()

# Size based on growth magnitude (scale up for visibility)
scatter1 = None
scatter2 = None

if len(df_growing) > 0:
    df_growing['bubble_size'] = (df_growing['revenue_growth_5y'] * 3000) + 200
if len(df_declining) > 0:
    df_declining['bubble_size'] = (abs(df_declining['revenue_growth_5y']) * 2000) + 100

# Plot growing companies with circles (filled)
if len(df_growing) > 0:
    scatter1 = plt.scatter(df_growing['pe_ratio'], df_growing['roe'],
                          s=df_growing['bubble_size'],
                          c=df_growing['debt_to_equity'],
                          cmap='RdYlGn_r',
                          alpha=0.7,
                          edgecolors='darkgreen',
                          linewidth=2.5,
                          marker='o',
                          label='Growing Revenue')

# Plot declining companies with X markers
if len(df_declining) > 0:
    scatter2 = plt.scatter(df_declining['pe_ratio'], df_declining['roe'],
                          s=df_declining['bubble_size'],
                          c=df_declining['debt_to_equity'],
                          cmap='RdYlGn_r',
                          alpha=0.7,
                          edgecolors='darkred',
                          linewidth=2.5,
                          marker='X',
                          label='Declining Revenue')

# Add ticker labels to each point
for idx, row in df.iterrows():
    plt.annotate(str(idx),
                (float(row['pe_ratio']), float(row['roe'])),
                xytext=(5, 5),
                textcoords='offset points',
                fontsize=9,
                fontweight='bold',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8))

# Add threshold lines
plt.axhline(y=0.15, color='r', linestyle='--', linewidth=2, alpha=0.7)
plt.axvline(x=20, color='g', linestyle='--', linewidth=2, alpha=0.7)

plt.title('The Analyst\'s Filter: Quality vs. Value in the Nordic 40', fontsize=14, fontweight='bold')
plt.xlabel('P/E Ratio (Lower = Better Value)', fontsize=11)
plt.ylabel('Return on Equity (Higher = Better Quality)', fontsize=11)

# Add colorbar for debt
if scatter1 is not None:
    cbar = plt.colorbar(scatter1, label='Debt-to-Equity Ratio')
    cbar.set_label('Debt-to-Equity (Lower = Less Risky)', fontsize=10)
elif scatter2 is not None:
    cbar = plt.colorbar(scatter2, label='Debt-to-Equity Ratio')
    cbar.set_label('Debt-to-Equity (Lower = Less Risky)', fontsize=10)

# Add custom legend
from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0], [0], marker='o', color='w', label='⬤ Growing Revenue (size = growth %)',
           markerfacecolor='gray', markeredgecolor='darkgreen', markersize=12, markeredgewidth=2),
    Line2D([0], [0], marker='X', color='w', label='✖ Declining Revenue (size = decline %)',
           markerfacecolor='gray', markeredgecolor='darkred', markersize=12, markeredgewidth=2),
    Line2D([0], [0], color='r', linestyle='--', linewidth=2, label='ROE > 15% (Quality Threshold)'),
    Line2D([0], [0], color='g', linestyle='--', linewidth=2, label='P/E < 20 (Value Threshold)')
]
plt.legend(handles=legend_elements, loc='upper right', fontsize=9)

plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('nordic_stocks_analysis.png', dpi=300, bbox_inches='tight')
print("Quality vs Value chart saved as 'nordic_stocks_analysis.png'")

# Create comprehensive financial metrics chart
fig, axes = plt.subplots(3, 2, figsize=(16, 12))
fig.suptitle('Nordic Stocks - Comprehensive Financial Metrics', fontsize=16, fontweight='bold')

# Shorten company names for better display
df['short_name'] = df.index

# 1. P/E Ratio
ax1 = axes[0, 0]
df_sorted = df.sort_values('pe_ratio')
colors1 = ['green' if x < 15 else 'orange' if x < 20 else 'red' for x in df_sorted['pe_ratio']]
ax1.barh(df_sorted['short_name'], df_sorted['pe_ratio'], color=colors1)
ax1.set_xlabel('P/E Ratio')
ax1.set_title('Price-to-Earnings Ratio (Lower = Better Value)')
ax1.axvline(x=15, color='green', linestyle='--', alpha=0.5, label='Good (<15)')
ax1.axvline(x=20, color='red', linestyle='--', alpha=0.5, label='High (>20)')
ax1.legend()

# 2. ROE
ax2 = axes[0, 1]
df_sorted = df.sort_values('roe')
roe_pct = df_sorted['roe'] * 100
colors2 = ['red' if x < 10 else 'orange' if x < 15 else 'green' for x in roe_pct]
ax2.barh(df_sorted['short_name'], roe_pct, color=colors2)
ax2.set_xlabel('ROE (%)')
ax2.set_title('Return on Equity (Higher = Better)')
ax2.axvline(x=15, color='green', linestyle='--', alpha=0.5, label='Good (>15%)')

# 3. P/B Ratio
ax3 = axes[1, 0]
df_sorted = df.sort_values('pb_ratio')
colors3 = ['green' if x < 2 else 'orange' if x < 4 else 'red' for x in df_sorted['pb_ratio']]
ax3.barh(df_sorted['short_name'], df_sorted['pb_ratio'], color=colors3)
ax3.set_xlabel('P/B Ratio')
ax3.set_title('Price-to-Book Ratio (Lower = Better Value)')
ax3.axvline(x=2, color='green', linestyle='--', alpha=0.5, label='Good (<2)')

# 4. Operating Margin
ax4 = axes[1, 1]
df_sorted = df.sort_values('operating_margin')
margin_pct = df_sorted['operating_margin'] * 100
colors4 = ['red' if x < 10 else 'orange' if x < 20 else 'green' for x in margin_pct]
ax4.barh(df_sorted['short_name'], margin_pct, color=colors4)
ax4.set_xlabel('Operating Margin (%)')
ax4.set_title('Operating Margin (Higher = Better Efficiency)')
ax4.axvline(x=20, color='green', linestyle='--', alpha=0.5, label='Good (>20%)')

# 5. Debt-to-Equity
ax5 = axes[2, 0]
df_sorted = df.sort_values('debt_to_equity')
colors5 = ['green' if pd.isna(x) or x < 0.5 else 'orange' if x < 1.0 else 'red' for x in df_sorted['debt_to_equity']]
ax5.barh(df_sorted['short_name'], df_sorted['debt_to_equity'].fillna(0), color=colors5)
ax5.set_xlabel('Debt-to-Equity Ratio')
ax5.set_title('Debt-to-Equity (Lower = Less Risky)')
ax5.axvline(x=0.5, color='green', linestyle='--', alpha=0.5, label='Low (<0.5)')
ax5.axvline(x=1.0, color='red', linestyle='--', alpha=0.5, label='High (>1.0)')

# 6. Revenue Growth
ax6 = axes[2, 1]
df_sorted = df.sort_values('revenue_growth_5y')
growth_pct = df_sorted['revenue_growth_5y'] * 100
colors6 = ['red' if x < 0 else 'orange' if x < 5 else 'green' for x in growth_pct]
ax6.barh(df_sorted['short_name'], growth_pct, color=colors6)
ax6.set_xlabel('Revenue Growth (%)')
ax6.set_title('5-Year Revenue Growth (Higher = Better)')
ax6.axvline(x=0, color='black', linestyle='-', alpha=0.3)
ax6.axvline(x=5, color='green', linestyle='--', alpha=0.5, label='Good (>5%)')

plt.tight_layout()
plt.savefig('nordic_stocks_metrics.png', dpi=300, bbox_inches='tight')
print("Financial metrics chart saved as 'nordic_stocks_metrics.png'")

print("\n" + "="*80)
print("ANALYSIS COMPLETE!")
print("Generated 3 visualization files:")
print("1. nordic_stocks_ranking.png - Investment score ranking")
print("2. nordic_stocks_analysis.png - Quality vs Value scatter plot")
print("3. nordic_stocks_metrics.png - Comprehensive financial metrics")
print("="*80)

from google.colab import drive
drive.mount('/content/drive')

